### ISSUE TITLE
IExplorer 8 issue

### ISSUE THREAD

**Issue by kiwi2b** [webfonts/Web-Fonts#28] opened 2013-01-30 12:19 UTC
Hi, great plugin for sure, but during testing I have an issue. Everything is good in internet explorer 9, but in ie8 the page fails to load. 

I notice in the staus bar its says "downloading data http://fastfonts.com... " , then after ages, I get the "Stop running the script?" dialogue box from IE. I click yes, and the page loads. Disabling the extension fixes the problem in that the page loads normally, but without the fonts of course.

How to fix? I'll ask the fonts.com people, but thought I'd ask here first. I can email a link if required, although the extension is disabled at the moment.

Thanks in advance for any ideas!

**Comment by kiwi2b** [comment] 2013-01-31 13:32
HI again, tested by switching in ie9 to compatibility mode, and a similar problem in that the website fails to load.
What do you think? Hope it's an easy one to fix.

**Comment by webfonts** [comment] 2013-02-01 05:38
Hey Kiwi, this sounds like some sort of problem between your host and Fonts.com's CDN.  I have tested my site in IE8 and IE9 compatibility mode and have not had the same problem.  In any case, this is not caused by the extension.

I have contacted Fonts.com and hope to get a response back soon.  - J

**Comment by kiwi2b** [comment] 2013-02-01 11:48
Thanks for checking. I've emailed fonts.com too. Let's hope for a fix!

**Comment by kiwi2b** [comment] 2013-02-02 04:04
Hi, the reply from fonts.com below. I fixed my tags and fixed the problem!

Fonts.com: Please note that there is currently a limitation in our script when interpreted by IE <9 if the page calling it has unclosed HTML tags that are normally required to be closed. We are currently investigating how we can update the script to allow it to be as resilient in older versions of IE as it is in other browsers. In the meantime, however, if you ensure that your page's tags are all properly closed it will eliminate the warning.

**Comment by webfonts** [comment] 2013-02-04 02:24
Thanks for sharing that Kiwi, I'll go ahead and close this issue. :)

**Closed as completed by webfonts** 2013-02-04 02:24 UTC
